/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "ExcellentShop-spigot"
include(":Core")
include(":NMS")
include(":V1_17_R1")
include(":V1_18_R2")
include(":V1_19_R2")

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://papermc.io/repo/repository/maven-public/")
    }
}