Name: '<green><b>Wool Market'
Pages: 1
Permission_Required: false
Transaction_Allowed:
  SELL: true
  BUY: true
Citizens:
  Attached_NPC: ''
Description:
- '<#d4d9d8>Wool with colors.'
Icon:
  Material: LIME_WOOL
