/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("su.nightexpress.excellentshop.java-conventions")
    id("io.papermc.paperweight.userdev")
}

dependencies {
    compileOnly(project(":NMS"))
    paperDevBundle("1.19.2-R0.1-SNAPSHOT")
}

description = "V1_19"

tasks {
    assemble {
        dependsOn(reobfJar)
    }
}