name: ExcellentShop
main: su.nightexpress.nexshop.ExcellentShop
version: ${version}
api-version: 1.19
authors: [ NightExpress, Nailm ]
description: Advanced 3 in 1 shop plugin with a lot of cool features!
load-before: [ ]
load-after:
  - name: NexEngine
    bootstrap: false
dependencies:
  server:
    NexEngine:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: OMIT
      required: false
      join-classpath: true
    CoinsEngine:
      load: OMIT
      required: false
      join-classpath: true
    GemsEconomy:
      load: OMIT
      required: false
      join-classpath: true
    PlayerPoints:
      load: OMIT
      required: false
      join-classpath: true
    WorldGuard:
      load: OMIT
      required: false
      join-classpath: true
