name: ExcellentShop
main: su.nightexpress.nexshop.ExcellentShop
version: ${version}
api-version: 1.19
authors: [ NightExpress, Nailm ]
description: Advanced 3 in 1 shop plugin with a lot of cool features!
load-before: [ ]
load-after:
  - name: NexEngine
    bootstrap: false
dependencies:
  - name: NexEngine
    required: true
    bootstrap: false
  - name: MewCore
    required: true
    bootstrap: false
  - name: Vault
    required: false
    bootstrap: false
  - name: GemsEconomy
    required: false
    bootstrap: false
  - name: PlayerPoints
    required: false
    bootstrap: false
  - name: WorldGuard
    required: false
    bootstrap: false
