Title: 'Price Settings'
Size: 27
Inventory_Type: CHEST

Format:
  Lore:
    Price:
      BUY:
        FLAT:
          - '<#fffc9a>▪ <#ddecee>Current:</#ddecee> %product_price_buy%'
          - ''
          - '<#ddecee>Price for players to <#fffc9a>purchase</#fffc9a> this item.'
          - ''
          - '<#9af7ff><b>Actions:'
          - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Change'
          - '<#ff9a9a>▪ <#ddecee>Right-Click:</#ddecee> Disable'
        FLOAT:
          - '<#fffc9a>▪ <#ddecee>Minimal:</#ddecee> %product_pricer_buy_min%'
          - '<#fffc9a>▪ <#ddecee>Maximal:</#ddecee> %product_pricer_buy_max%'
          - ''
          - '<#ddecee>Range of values to generate'
          - '<#ddecee>purchase price from.'
          - ''
          - '<#9af7ff><b>Actions:'
          - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Change Min'
          - '<#9af7ff>▪ <#ddecee>Right-Click:</#ddecee> Change Max'
        DYNAMIC:
          - '<#fffc9a>▪ <#ddecee>Minimal:</#ddecee> %product_pricer_buy_min%'
          - '<#fffc9a>▪ <#ddecee>Maximal:</#ddecee> %product_pricer_buy_max%'
          - ''
          - '<#ddecee>Range of values to limit'
          - '<#ddecee>min. and max. purchase price.'
          - '<#ddecee>(it will never exceed these values)'
          - ''
          - '<#9af7ff><b>Actions:'
          - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Change Min'
          - '<#9af7ff>▪ <#ddecee>Right-Click:</#ddecee> Change Max'
      SELL:
        FLAT:
          - '<#fffc9a>▪ <#ddecee>Current:</#ddecee> %product_price_sell%'
          - ''
          - '<#ddecee>Price for players to <#fffc9a>sell<#ddecee> this item.'
          - ''
          - '<#9af7ff><b>Actions:'
          - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Change'
          - '<#ff9a9a>▪ <#ddecee>Right-Click:</#ddecee> Disable'
        FLOAT:
          - '<#fffc9a>▪ <#ddecee>Minimal:</#ddecee> %product_pricer_sell_min%'
          - '<#fffc9a>▪ <#ddecee>Maximal:</#ddecee> %product_pricer_sell_max%'
          - ''
          - '<#ddecee>Range of values to generate'
          - '<#ddecee>sell price from.'
          - ''
          - '<#9af7ff><b>Actions:'
          - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Change Min'
          - '<#9af7ff>▪ <#ddecee>Right-Click:</#ddecee> Change Max'
        DYNAMIC:
          - '<#fffc9a>▪ <#ddecee>Minimal:</#ddecee> %product_pricer_sell_min%'
          - '<#fffc9a>▪ <#ddecee>Maximal:</#ddecee> %product_pricer_sell_max%'
          - ''
          - '<#ddecee>Range of values to limit'
          - '<#ddecee>min. and max. sell price.'
          - '<#ddecee>(it will never exceed these values)'
          - ''
          - '<#9af7ff><b>Actions:'
          - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Change Min'
          - '<#9af7ff>▪ <#ddecee>Right-Click:</#ddecee> Change Max'

Content:
  return:
    Priority: 5
    Slots: 22
    Type: RETURN
    Item:
      Material: PLAYER_HEAD
      Head_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmU5YWU3YTRiZTY1ZmNiYWVlNjUxODEzODlhMmY3ZDQ3ZTJlMzI2ZGI1OWVhM2ViNzg5YTkyYzg1ZWE0NiJ9fX0=
      Name: '<#e3fbf9>(↓) <b>Return'

Editor:
  PRODUCT_CHANGE_PRICE_TYPE:
    Priority: 5
    Slots: 4
    Type: PRODUCT_CHANGE_PRICE_TYPE
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmI5Mjk5YjcyNGM1ZDM0YWM5M2VkZTc1NjAxZGZlYjBiZGE1NzhkNzBiOGY0ZDdmODJkNzY3NmYwYzZjMTE0YSJ9fX0='
      Name: '<#fffc9a><b>Price Type'
      Lore:
        - '<#fffc9a>▪ <#ddecee>Current:</#ddecee> %product_price_type%'
        - ''
        - '<#ddecee>Depends on a price type, this menu'
        - '<#ddecee>will have different settings.'
        - ''
        - '<#ff9a9a>[!]<#ddecee> Previous settings will be <#ff9a9a>lost<#ddecee>!'
        - '<#ff9a9a>[!]<#ddecee> Make sure you have <#ff9a9a>permission<#ddecee> to do that.'
        - ''
        - '<#9af7ff><b>Actions:'
        - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Toggle'

  PRODUCT_CHANGE_PRICE_BUY:
    Priority: 5
    Slots: 10
    Type: PRODUCT_CHANGE_PRICE_BUY
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmY2Yjg1ZjYyNjQ0NGRiZDViZGRmN2E1MjFmZTUyNzQ4ZmU0MzU2NGUwM2ZiZDM1YjZiNWU3OTdkZTk0MmQifX19'
      Name: '<#fffc9a><b>Buy Price'
      Lore:
        - '%price_buy%'

  PRODUCT_CHANGE_PRICE_SELL:
    Priority: 5
    Slots: 11
    Type: PRODUCT_CHANGE_PRICE_SELL
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTlkYmVkNTIyZThkZTFhNjgxZGRkZDM3ODU0ZWU0MjY3ZWZjNDhiNTk5MTdmOWE5YWNiNDIwZDZmZGI5In19fQ=='
      Name: '<#fffc9a><b>Sell Price'
      Lore:
        - '%price_sell%'

  PRODUCT_CHANGE_PRICE_FLOAT_REFRESH:
    Priority: 5
    Slots: 15
    Type: PRODUCT_CHANGE_PRICE_REFRESH
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDJkOTkzNDJiZTY3MTU2Y2VmNDhiNTBhOTcxOTI5ODkyMjJkNTY5YjQ0NjA5Mjg5OWNjMjMzNDc1NDJlNzFhYSJ9fX0='
      Name: '<#fffc9a><b>Refresh Settings'
      Lore:
        - '<#fffc9a>▪ <#ddecee>Days:</#ddecee> %product_pricer_float_refresh_days%'
        - '<#fffc9a>▪ <#ddecee>Times:'
        - '<#fffc9a>%product_pricer_float_refresh_times%'
        - ''
        - '<#ddecee>Sets, when the product price'
        - '<#ddecee>will be refreshed. Until that, the'
        - '<#ddecee>previous generated price will be used.'
        - ''
        - '<#ff9a9a><b>NOTE:'
        - '<#ddecee>You have to provide at least <#ff9a9a>ONE'
        - '<#ddecee>day and time for the'
        - '<#ddecee>float price feature to work.'
        - ''
        - '<#9af7ff><b>Actions:'
        - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Add Day'
        - '<#9af7ff>▪ <#ddecee>Shift-Left:</#ddecee> Clear Days'
        - '<#9af7ff>▪ <#ddecee>Right-Click:</#ddecee> Add Time'
        - '<#9af7ff>▪ <#ddecee>Shift-Right:</#ddecee> Clear Times'

  PRODUCT_CHANGE_PRICE_DYNAMIC_INITIAL:
    Priority: 5
    Slots: 15
    Type: PRODUCT_CHANGE_PRICE_INITIAL
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODI0Zjc2OWM5NDUwZjIyZTQ4NGUwODljYTAyZTMyNGZlMzdiMThmNGMxOGVmMjk2MDIxODcxYmE0YWQwYzM5NiJ9fX0='
      Name: '<#fffc9a><b>Initial Price'
      Lore:
        - '<#fffc9a>▪ <#ddecee>Buy:</#ddecee> %product_pricer_dynamic_initial_buy%'
        - '<#fffc9a>▪ <#ddecee>Sell:</#ddecee> %product_pricer_dynamic_initial_sell%'
        - ''
        - '<#ddecee>Sets initial price for the product.'
        - '<#ddecee>These values will be used as <#fffc9a>default'
        - '<#ddecee>ones, and to calculate <#fffc9a>further<#ddecee> price.'
        - ''
        - '<#9af7ff><b>Actions:'
        - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Change Buy'
        - '<#9af7ff>▪ <#ddecee>Right-Click:</#ddecee> Change Sell'

  PRODUCT_CHANGE_PRICE_DYNAMIC_STEP:
    Priority: 5
    Slots: 16
    Type: PRODUCT_CHANGE_PRICE_STEP
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2U0ZjJmOTY5OGMzZjE4NmZlNDRjYzYzZDJmM2M0ZjlhMjQxMjIzYWNmMDU4MTc3NWQ5Y2VjZDcwNzUifX19'
      Name: '<#fffc9a><b>Price Step'
      Lore:
        - '<#fffc9a>▪ <#ddecee>Buy:</#ddecee> %product_pricer_dynamic_step_buy%'
        - '<#fffc9a>▪ <#ddecee>Sell:</#ddecee> %product_pricer_dynamic_step_sell%'
        - ''
        - '<#ddecee>Price will be <#a5ff9a>increased<#ddecee> by <#a5ff9a>%product_pricer_dynamic_step_buy%<#ddecee> on each'
        - '<#ddecee>purchase and <#ff9a9a>decreased<#ddecee> by <#ff9a9a>%product_pricer_dynamic_step_sell%'
        - '<#ddecee>on each sale.'
        - ''
        - '<#9af7ff><b>Actions:'
        - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Change Buy'
        - '<#9af7ff>▪ <#ddecee>Right-Click:</#ddecee> Change Sell'