Title: 'Shop Settings'
Size: 9

Content:

  SHOP_CHANGE_NAME:
    Item:
      Material: NAME_TAG
      Name: '&e&lShop Name'
      Lore:
        - '&b&l[?] Current:'
        - '&a%shop_name%'
        - ' '
        - '&6&l[?] Description:'
        - '&7Sets the shop display name. This'
        - '&7name is displayed above the shop.'
        - ' '
        - '&x&5&5&e&1&3&6&l[>] Actions:'
        - '&x&8&6&d&e&2&aLeft-Click to &fChange'
    Type: SHOP_CHANGE_NAME
    Slots: 0

  SHOP_CHANGE_TYPE:
    Item:
      Material: REDSTONE
      Name: '&e&lShop Type'
      Lore:
        - '&b&l[?] Current:'
        - '&a%shop_type%'
        - ' '
        - '&6&l[?] Description:'
        - '&7Sets the shop type.'
        - ' '
        - '&e&l[!] Note:'
        - '&x&F&F&C&3&0&0Admin shops have unlimited funds and'
        - '&x&F&F&C&3&0&0items.'
        - ' '
        - '&e&l[!] Note:'
        - '&x&F&F&C&3&0&0Player shop have to be restocked'
        - '&x&F&F&C&3&0&0with items and funds.'
        - ' '
        - '&x&5&5&e&1&3&6&l[>] Actions:'
        - '&x&8&6&d&e&2&aLeft-Click to &fToggle'
    Type: SHOP_CHANGE_TYPE
    Slots: 1

  SHOP_CHANGE_TRANSACTIONS:
    Item:
      Material: WRITABLE_BOOK
      Name: '&e&lEnabled Transactions'
      Lore:
        - '&b&l[?] Current:'
        - '&aBuying Enabled: &f%shop_buy_allowed%'
        - '&aSelling Enabled: &f%shop_sell_allowed%'
        - ' '
        - '&6&l[?] Description:'
        - '&7Enables or disables Buying and Selling'
        - '&7in the shop.'
        - ' '
        - '&x&5&5&e&1&3&6&l[>] Actions:'
        - '&x&8&6&d&e&2&aLeft-Click to &fToggle Buying'
        - '&x&8&6&d&e&2&aRight-Click to &fToggle Selling'
    Type: SHOP_CHANGE_TRANSACTIONS
    Slots: 2

  SHOP_CHANGE_PRODUCTS:
    Item:
      Material: CHEST
      Name: '&e&lShop Products'
      Lore:
        - '&6&l[?] Description:'
        - '&7Here you can manage your products'
        - '&7and add new ones.'
        - ' '
        - '&x&5&5&e&1&3&6&l[>] Actions:'
        - '&x&8&6&d&e&2&aLeft-Click to &fNavigate'
    Type: SHOP_CHANGE_PRODUCTS
    Slots: 3

  SHOP_BANK:
    Item:
      Material: EMERALD
      Name: '&e&lShop Bank'
      Lore:
        - '&b&l[?] Current:'
        - '&aBalance:'
        - '&a%shop_bank_balance%'
        - ' '
        - '&6&l[?] Description:'
        - '&7Bank is where you deposit funds'
        - '&7for the shop to be able'
        - '&7to purchase items from players. And'
        - '&7where all incoming funds from sales'
        - '&7are stored for you to withdraw'
        - '&7them later.'
        - ' '
        - '&c&l[!] Warning:'
        - '&x&C&7&0&0&3&9If shop don''t have enough funds,'
        - '&x&C&7&0&0&3&9players won''t be able to sell'
        - '&x&C&7&0&0&3&9into it'
        - ' '
        - '&x&5&5&e&1&3&6&l[>] Actions:'
        - '&x&8&6&d&e&2&aLeft-Click to &fDeposit'
        - '&x&8&6&d&e&2&aRight-Click to &fWithdraw'
    Type: SHOP_BANK
    Slots: 4

  SHOP_DELETE:
    Item:
      Material: BARRIER
      Name: '&e&lDelete Shop'
      Lore:
        - '&6&l[?] Description:'
        - '&7Permanently deletes this shop.'
        - ' '
        - '&c&l[!] Warning:'
        - '&x&C&7&0&0&3&9You have to remove all product'
        - '&x&C&7&0&0&3&9items from the container first.'
        - ' '
        - '&x&5&5&e&1&3&6&l[>] Actions:'
        - '&x&8&6&d&e&2&aShift-Left to &fDelete'
    Type: SHOP_DELETE
    Slots: 8