Title: 'Shop Settings'
Size: 9
Inventory_Type: CHEST

Content:
  SHOP_CHANGE_NAME:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjVhMTlhZjBlNjFjYTQyNTMyYzA1OTlmYTBhMzkxNzUzZGY2YjcxZjlmYTRhMTc3ZjFhYTliMWQ4MWZlNmVlMiJ9fX0='
      Name: '<#ee9aff><b>Shop Name'
      Lore:
        - '<#ee9aff>▪ <#ddecee>Current:</#ddecee> %shop_name%'
        - ''
        - '<#ddecee>Shop name to be displayed in'
        - '<#ddecee>GUI and showcase.'
        - ''
        - '<#9af7ff><b>Actions:'
        - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Change'
    Type: SHOP_CHANGE_NAME
    Slots: 0
    Priority: 5

  SHOP_CHANGE_TYPE:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmRhOTExNDM3YjRlY2ZhYTNjMTg5NDE2MjIxN2MwMWI2OGE1NWM4OWJiMmY0ZDQ5MjczNDVjZTVjNzk0In19fQ=='
      Name: '<#ee9aff><b>Shop Type'
      Lore:
        - '<#ee9aff>▪ <#ddecee>Current:</#ddecee> %shop_type%'
        - ''
        - '<#ddecee>Setting shop as <#ee9aff>admin shop<#ddecee> will'
        - '<#ddecee>make it to have unlimited funds and items.'
        - ''
        - '<#ff9a9a>[!]<#ddecee> Make sure you have <#ff9a9a>permission<#ddecee> to use it.'
        - ''
        - '<#9af7ff><b>Actions:'
        - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Toggle'
    Type: SHOP_CHANGE_TYPE
    Slots: 1
    Priority: 5

  SHOP_CHANGE_TRANSACTIONS:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTgzOTg0ODU1M2NhYmVkOTc3ZThkNWNjOTc2ZDQ0Y2JhMmVhYWVmZTFkYTQ0NjE4N2U4NTJlZGVlMTZiODcwZSJ9fX0='
      Name: '<#ee9aff><b>Trade Mode'
      Lore:
        - '<#ee9aff>▪ <#ddecee>Buying:</#ddecee> %shop_buy_allowed%'
        - '<#ee9aff>▪ <#ddecee>Selling:</#ddecee> %shop_sell_allowed%'
        - ''
        - '<#ddecee>Enable/disable certain operations in the shop.'
        - ''
        - '<#9af7ff><b>Actions:'
        - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Toggle Buying'
        - '<#9af7ff>▪ <#ddecee>Right-Click:</#ddecee> Toggle Selling'
    Type: SHOP_CHANGE_TRANSACTIONS
    Slots: 2
    Priority: 5

  SHOP_CHANGE_PRODUCTS:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTAwZDI4ZmY3YjU0M2RkMDg4ZDAwNGIxYjFmOTViMzhkNDQ0ZWEwNDYxZmY1YWUzYzY4ZDc2YzBjMTZlMjUyNyJ9fX0='
      Name: '<#ee9aff><b>Shop Products'
      Lore:
        - '<#ddecee>Here you can <#ee9aff>create<#ddecee> and <#ee9aff>manage'
        - '<#ddecee>products of your shop.'
        - ''
        - '<#9af7ff><b>Actions:'
        - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Open'
    Type: SHOP_CHANGE_PRODUCTS
    Slots: 3
    Priority: 5

  SHOP_BANK:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjg4OWNmY2JhY2JlNTk4ZThhMWNkODYxMGI0OWZjYjYyNjQ0ZThjYmE5ZDQ5MTFkMTIxMTM0NTA2ZDhlYTFiNyJ9fX0='
      Name: '<#ee9aff><b>Shop Bank'
      Lore:
        - '<#ee9aff>▪ <#ddecee>Balance:</#ddecee> %shop_bank_balance%'
        - ''
        - '<#ddecee>Bank is used to store funds of your shop.'
        - '<#ddecee>Shop will <#a5ff9a>gain<#ddecee> funds from sales,'
        - '<#ddecee>and <#ff9a9a>spend<#ddecee> them for purchases.'
        - ''
        - '<#9af7ff><b>Actions:'
        - '<#9af7ff>▪ <#ddecee>Left-Click:</#ddecee> Open'
    Type: SHOP_BANK
    Slots: 4
    Priority: 5

  SHOP_DELETE:
    Item:
      Material: PLAYER_HEAD
      Head_Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjQ2NWY4MGJmMDJiNDA4ODg1OTg3YjAwOTU3Y2E1ZTllYjg3NGMzZmE4ODMwNTA5OTU5N2EzMzNhMzM2ZWUxNSJ9fX0='
      Name: '<#ff9a9a><b>Delete Shop'
      Lore:
        - '<#ddecee>Permanently deletes the shop.'
        - ''
        - '<#ff9a9a><b>NOTE:'
        - '<#ddecee>You have to remove all items'
        - '<#ddecee>from the container first.'
        - ''
        - '<#9af7ff><b>Actions:'
        - '<#9af7ff>▪ <#ddecee>Shift-Right:</#ddecee> Delete'
    Type: SHOP_DELETE
    Slots: 8
    Priority: 5